import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Arabic, Noto_Sans_Hebrew } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { DirectionProvider } from "@/components/ui/direction";
import { LanguageProvider } from "@/components/language-provider";

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ['latin'],
  variable: '--font-arabic'
});

const notoSansHebrew = Noto_Sans_Hebrew({
  subsets: ['latin'],
  variable: '--font-hebrew',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" className={`${geistSans.variable} ${geistMono.variable} ${notoSansArabic.variable} ${notoSansHebrew.variable} antialiased`} suppressHydrationWarning dir="rtl">
      <body>
        <DirectionProvider direction="rtl">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LanguageProvider>
              {children}
            </LanguageProvider>
          </ThemeProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
